### ISSUE TITLE
Add download command

### ISSUE THREAD

**Issue by astronouth7303** [duckinator/bork#10]
For projects that have CIs doing their builds, being able to download the files is pretty helpful.

* From github releases
* From test.pypi.org
* From pypi.org (less useful, but for completeness?)

**Comment by duckinator** [comment]
@astronouth7303 could you elaborate on what it'd do, so I can make sure I understand correctly? Like, is this for verifying that the upload worked properly, or what?

**Comment by astronouth7303** [comment]
Just grab the package files from common repos and toss them wither in cwd or `dist`.

**Comment by astronouth7303** [comment]
My use case: Part of the ppb-vector release process involves downloading CI-built artifacts to upload them to prod pypi.org.

**Comment by duckinator** [comment]
The ability to download files from GitHub releases has been merged into master, now.

![Screenshot_20190715_111606](https://user-images.githubusercontent.com/39698/61227255-fccaf780-a6f1-11e9-8516-0ce26d04f3fc.png)

At the moment the defaults are to download only `*.pyz` and to put the files in `downloads/`.

**Comment by duckinator** [comment]
#19 adds the ability to download from PyPI. Once that's working, supporting test.pypi.org should be relatively straightforward.

**Comment by duckinator** [comment]
#20 will add support for downloading + releasing to test.pypi.org.

**Comment by duckinator** [comment]
The next release will have this.
