### ISSUE TITLE
Option for using Travis or CircleCi

### ISSUE THREAD

**Issue by isakal** [duckinator/bork#102]
Add an input option to choose a CI system of choice
- travis
- circleci
- codeship
- gitlab ci

**Comment by astronouth7303** [comment]
I'm not sure what you mean? `bork` is a local installable tool.

`bork` does use Cirrus CI, but for its own development. The code is not tied to it.

In fact, I believe that `bork` has 0 CI integration.

**Comment by duckinator** [comment]
Could you elaborate, @isakal? As @astronouth7303 said above, `bork` has no integration with any CI system whatsoever. I use Cirrus CI to test `bork` itself, but that has no relation to how other people use it. If you have Python 3.5+ with pip, you can install bork and should be fine.

**Comment by isakal** [comment]
Sorry for late response,
I thought bork was some kind of pre-commit tool. It turns out bork is `git clone` and `setuptools` simplified and easier to use.
This issue can be closed.
