### ISSUE TITLE
Feature Request: Flags related to logging

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#143]
I'm thinking `--log <level>` and `--logfile <filename>`.

WRT `--log <level>`, you can just pass the value as a string along to `logging.getLogger().setLevel('<level>')` to set it on the root logger, and it'll propagate to everything else.

WRT `--logfile`, maybe something like this?: `logging.addHandler(logging.FileHandler(filename, mode='w'))`

`logging.basicConfig(handlers=(...))` may be useful, idk.

**Comment by duckinator** [comment]
cc @astronouth7303 @nbraud

**Comment by duckinator** [comment]
It looks like `bork.cli.main` does some logging-related stuff, including defaulting log level to `INFO`. It may make sense to pull that out into a function in `bork.log`.

**Comment by astronouth7303** [comment]
I usually find that you quickly get to the point you just need a dictConfig (eg, to shush some libraries).

**Comment by duckinator** [comment]
So, I just realized  that `--verbose` already sets the log level to `INFO` (instead of the default `WARNING`). Perhaps it'd make more sense to just add a separate `--debug` flag? (Similar to many programs' "very verbose" output if you do `-vv`.)

**Comment by duckinator** [comment]
Yeah, I'm just going to add `--debug` and `--logfile <filename>`.`

**Comment by duckinator** [comment]
I'm not bothering with `--logfile`, for now, because it got pretty complex in practice and isn't _super_ useful.
