### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#163]
I'd like to automate bork's release process.

What this specifically means in this case is: I want a commit to master which increments the value of `bork.__version__` to initiate a new release.

**Comment by duckinator** [comment]
Once #3 ("add support for GitHub releases") is resolved, I will be able to run `bork clean && bork build && bork run test && bork release` and it'll:

1. Release to PyPI.
2. Release to GitHub Releases, thus causing a new tag to be created.
3. Due to the new tag being created, Cirrus CI will build+push an updated container image to Docker Hub.

At that point, all that is required is (in theory, at least) to automate running that sequence of commands whenever the value of `__version__` (in `bork/__init__.py`) is changed.

A good starting point would be to have a [manual task](https://cirrus-ci.org/guide/writing-tasks/#manual-tasks) on Cirrus CI that handles the release process. At that point, it is just a matter of automating when it's triggered.

**Comment by astronouth7303** [comment]
The best I have for this is [setuptools-scm](https://pypi.org/project/setuptools-scm/) and some cirrus tasks ([gqlmod](https://github.com/gqlmod/gqlmod/blob/master/.cirrus.yml) [ppb](https://github.com/ppb/pursuedpybear)) to do the build and publish.

Alternatively, I could get back to Go Build It and do a version that actually uploads stuff somewhere.

**Comment by duckinator** [comment]
Over in #164 I  managed to make a task that only exists when `bork/__init__.py` changes, and since nothing but `__version__` is defined in that file right now that means it only updates when `__version__` is changed.

I think, in theory, I could get this to do PyPi releases if I configure the `TWINE_USERNAME`/`TWINE_PASSWORD` environment variables. I'd like to avoid putting my _actual freaking password_ in an environment variable (even encrypted), though, so I'm poking at PyPi's docs atm.

**Comment by duckinator** [comment]
https://pypi.org/help/#apitoken

> **How can I use API tokens to authenticate with PyPI?**
> [...]
> To use an API token:
> * Set your username to __token__
> * Set your password to the token value, including the pypi- prefix

well, that's simple enough lmao

**Comment by duckinator** [comment]
I used this for the release of v5.0.0b5, and successfully released to:

- [PyPi](https://pypi.org/project/bork/5.0.0b5/)
- [GitHub Releases](https://github.com/duckinator/bork/releases/tag/v5.0.0b5)
- [Docker Hub](https://hub.docker.com/layers/duckinator/bork/v5.0.0b5/images/sha256-3e6f1b5ef062b8d766cbc12e62827d376b40f0f0412f2ec2e2433e0bcd2f3e94?context=repo)
