### ISSUE TITLE
container: pip warnings:

### ISSUE THREAD

**Issue by AstraLuma** [duckinator/bork#191]
https://cirrus-ci.com/task/5187350944808960

```
bork build
pep517.envbuild ERROR WARNING: You are using pip version 20.2; however, version 20.2.2 is available.
pep517.envbuild ERROR You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
pep517.envbuild ERROR WARNING: You are using pip version 20.2; however, version 20.2.2 is available.
pep517.envbuild ERROR You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
running sdist
running egg_info
```

**Comment by duckinator** [comment]
What happened is Bork v5.0.0 was released on August 3 and then pip made releases on the August 4th and August 11.

It looks like the Docker images for Python are rebuilt whenever pip is released, so this could probably be solved by re-building the Docker image.

**Comment by duckinator** [comment]
I'd like to automate this &mdash; or at least get automated alerts &mdash; somehow, but for now I manually re-ran the `Release on Docker Hub` task: https://cirrus-ci.com/task/6565860963778560

When that's done, the warnings should be fixed.

**Comment by duckinator** [comment]
This is fixed now. :+1:
