### ISSUE TITLE
Re-build Docker Hub image on Python dependency releases?

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#192]
It may make sense to re-build the Docker Hub image when Pip is released.

There's a RSS feed for Pip releases: https://pypi.org/rss/project/pip/releases.xml
It also looks like the Python Docker image is re-released whenever Pip is: https://hub.docker.com/layers/python/library/python/3.8-slim/images/sha256-282fc7428f74cf3317d78224349b9215f266fc9cb4197cce58dad775cb565ed3

I'm not sure if I want to automatically rebuild+push the Docker Hub image, but it'd be nice to at least get an alert somehow that would let me manually initiate the process.

**Comment by duckinator** [comment]
In this case, I went to <https://cirrus-ci.com/github/duckinator/bork/v5.0.0>, found the relevant build, and re-ran the `Release on Docker Hub` task.

However, Cirrus seems extremely confused by this: https://cirrus-ci.com/task/6565860963778560

![Screenshot_20200828_155153](https://user-images.githubusercontent.com/39698/91609985-6a61d380-e946-11ea-880f-7ed42784612b.png)

So perhaps it'd make more sense to create _new_ builds?

**Comment by AstraLuma** [comment]
For xonsh, I just rebuild nightly.

**Comment by duckinator** [comment]
An alternative to this would be using multiple tags for each release:

1. `v$MAJOR.$MINOR.$PATCH` (allow nothing to change; pin exact version)
2. `v$MAJOR.$MINOR` (allow patch version to change; you get bug fixes)
3. `v$MAJOR` (allow patch and minor version to change; you get bug fixes and new features, but [hopefully] no breaking changes)

**Comment by duckinator** [comment]
This should've been a hint that Bork's dependencies weren't well-defined.

Pip is now an explicit dependency, and should've been one since zipapp support was added. If we ever encounter bugs that are fixed by requiring a newer pip version, we can start restricting the version of pip we depend on.
