### ISSUE TITLE
Improve how zipapps are built by using bdists

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#196]
What prompted this: Files with a `.py~` suffix are backups (e.g. from vim) and `__pycache__` is cached files. Bork probably shouldn't include these in distributions.

The current approach to installing:

1. make an empty directory
2. copy the source (./emanate, ./bork, etc)
3. grab the list of `install_requires` dependencies from setup.cfg, then run (basically) `<python executable> -m pip install --target <directory from step 1> dep1 dep2 ... depN`

However, step 2 of the current approach already requires a bdist be built, so why not this?:

1. ensure bdist is built
2. grab the list of `install_requires` dependencies from setup.cfg, and run (basically) `<python executable> -m pip install --target <directory from step 1> dep1 dep2 ... depN <bdist path>`

**Comment by AstraLuma** [comment]
better thought: skip the `install_requires` parsing and just have pip do that for you.

So it's `<python executable> -m pip install --target <directory from step 1> <bdist path>`

**Comment by duckinator** [comment]
Yup, I think that'd work. If it does, then all of this:

- https://github.com/duckinator/bork/blob/master/bork/builder.py#L34-L57
- https://github.com/duckinator/bork/blob/master/bork/builder.py#L100-L101

... would possibly just become this:

```python
bdist_path = ... # TODO
subprocess.check_call([sys.executable, '-m', 'pip', 'install', '--target', dest, bdist_path])
```
