### ISSUE TITLE
Support projects without setup.cfg

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#228]
It seems like setup.cfg is used exclusively for the project name. Providing a way to specify it in pyproject.toml might be useful, for folks not using setuptools (or who are doing a quick migration and still use setup.py).

I explicitly do not want to try to process setup.py. It can't be done without running it.

**Comment by duckinator** [comment]
This also appears specific to ZipApps.

**Comment by nbraud** [comment]
Given that people are supposed to have a `pyproject.toml` when using `bork`, I think it would indeed make sense to support configuring `bork` through that file.

If we do that, I think it would be a good idea to deprecate configuring `bork` through `setup.cfg`.  Since that's more-or-less a breaking change, we might want to add a warning in bork v6, and stop looking at `setup.cfg` in bork v7 (or maybe even assert there's no bork-related config in there)

**Comment by duckinator** [comment]
@nbraud the value from setup.cfg that is used is metadata.name. e.g., from https://github.com/duckinator/bork/blob/main/setup.cfg:

```
[metadata]
name = bork
```

That's the only place it's used. Given that it's always there with setuptools, and would be redundant to put in both, I'm wondering about checking pyproject.toml and falling back to setup.cfg?

**Comment by duckinator** [comment]
I found a potential repo I can use as a testcase for driving this functionality to completion: https://github.com/openpreserve/fido

I downloaded the latest release, and made very few changes and was able to make a zipapp of it.

First, I added a `pyproject.toml` with these contents (#280 would render this unnecessary):

```
[tool.bork.zipapp]
enabled = true
main = "fido.fido:main"
```

And added this at the start of their `setup.cfg` (addressed by this issue):

```
[metadata]
name=fido
```

**Comment by duckinator** [comment]
If this falls back to setup.cfg, it's not a breaking change, so I put it in the v6.1.0 milestone.

**Comment by duckinator** [comment]
There's a specification for this, now: https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

And setuptools is on board: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

Closing this in favor of #312.
