### ISSUE TITLE
Improve the error reporting

### ISSUE THREAD

**Issue by nbraud** [duckinator/bork#242]
Continuation of #240.  Currently, the error and warning logs can get pushed off the screen by the backtrace.

**Comment by nbraud** [comment]
@duckinator What would you think of logging the backtrace to a temporary file and giving a link to that (unless the user requests verbose errors via a CLI flag or an environment variable)

**Comment by duckinator** [comment]
@nbraud I'd be okay with that. Do you think we should tie it to `--verbose`, `--debug`, or something else?

(Sorry for the slow response, in the process of getting a new house.)

**Comment by nbraud** [comment]
> @nbraud Do you think we should tie it to `--verbose`, `--debug`, or something else?

Yes, I think it would make sense not to display the backtrace (and only the exception itself) unless some flag is set, and unconditionally save it to a text file.

> (Sorry for the slow response, in the process of getting a new house.)

I know, hon, and it's entirely fine.  I've not been particularly responsive myself either in the last couple of months, and I'm not even moving  ;3

**Comment by duckinator** [comment]
Added to the v7.0.0 milestone because this feels like a breaking change and v6.0.0 is already going to be big.

**Comment by duckinator** [comment]
May be closed by #359.
