### ISSUE TITLE
Add support for GitHub releases

### ISSUE THREAD

**Issue by astronouth7303** [duckinator/bork#3]
Add uploading to GitHub releases.

Basically, I would like to replace https://github.com/ppb/ppb-vector/blob/master/.ci/upload-build.sh with a bork call.

**Comment by nbraud** [comment]
I'm having a stab at this.

**Comment by duckinator** [comment]
When bors finishes merging #103, this will be far enough along that `bork release --dry-run` with GitHub releases enabled will work and know what files to upload.

The only part that will remain is the actual upload process. So, we're getting there!

**Comment by duckinator** [comment]
Now that #144 has been merged, we're at the point that:

- `bork release --dry-run` with GitHub releases enabled will work and know what files to upload.
- there is a `GithubApi` class to handle the process, but it is not used.

I believe all that's left is integrating that class.

**Comment by duckinator** [comment]
GitHub Release support also should be implemented in terms of creating a draft release, then marking that draft as published. The reason for this is to avoid the scenario of accidentally only releasing to GitHub Releases _or_ PyPi if something breaks:

1. Publish draft to GitHub Releases.
2. Release to PyPi.
3. If everything succeeded, mark the GitHub Releases draft as published.

**Comment by duckinator** [comment]
This is going to be in v5.0.0, including using GitHub Release drafts, but needs to be documented.

**Comment by duckinator** [comment]
This has worked for multiple beta releases and has been mostly documented. I'll add a note about the `BORK_GITHUB_TOKEN` environment variable before releasing, and I think that's all I missed. It'll be in v5.0.0.
