### ISSUE TITLE
Add ability to run test suite

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#30]
To my knowledge, there's no PEP for testing that's equivalent to [PEP 517](https://www.python.org/dev/peps/pep-0517/).

Given this, the simplest approach is probably just to add aliases that just run a shell command.

Below I'll document some approaches, with some pros and cons of each.

All of these examples assume a `setup.cfg` with a section alog the lines of this:

```
[options.extras_require]
linting =
    flake8
    pylint

testing =
    bork[linting]
    pytest
    pytest-flake8
    pytest-pylint

[bork.aliases]
test = pytest --pylint --flake8 --verbose
```

## Generic aliases, no special syntax

Run with: `bork test`

Pros:
- only one program to work with!

Cons:
- confusing as to whether a command is built-in or not
- potential for conflicting with future bork sub-commands

## Generic aliases, with a prefix

Run with: `bork +test` (Possibly different single-character prefix.)

Pros:
- only one program to work with!
- disambiguates sub-commands vs aliases

Cons:
- arguably a bit of a kludge

## Generic aliases, subcommand

Run with: `bork run test`

Pros:
- only one program to work with!
- disambiguates sub-commands vs aliases

Cons:
- longer command to type

## Generic aliases, separate program

Run with: `bork-run test`

Pros:
- disambiguates sub-commands vs aliases

Cons:
- longer command to type
- two programs to work with. :(

**Comment by duckinator** [comment]
I'm leaning towards `bork run <command>`.

**Comment by nbraud** [comment]
@duckinator As said out-of-band, I believe this is pretty good, using `bork run` and configuration in `pyproject.toml`.
Found some minor things while reviewing the implementation, which I'm fixing in #40.
