### ISSUE TITLE
Should `bork download` be removed?

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#336]
Basically:

- I'm not sure I have ever used `bork download` aside from testing the functionality.
- I literally don't know why I added it.
- It adds a lot of complexity to the codebase, for very little benefit.

I'm wondering if it makes sense to remove `bork download` entirely, or possibly split it out into a separate tool.

**Comment by duckinator** [comment]
@nbraud @AstraLuma what're your thoughts on this?

**Comment by AstraLuma** [comment]
It looks like it would be useful for artifact handling in CI? But

1. Very few projects publish python packages in github releases--it's just easier to use PyPI
2. I'm not sure what CI flow would involve downloading a previously-built package through non-standard channels

**Comment by duckinator** [comment]
That's why I'm thinking it might make sense to split it out into its own tool. It's useful, but in different situations than bork is useful.

**Comment by duckinator** [comment]
Independently of it being removed: as long as it exists, the definition of `bork.api.DOWNLOAD_SOURCES` should be moved into `bork.api.download()` so it doesn't affect other commands.

**Comment by duckinator** [comment]
Closing in favor of #357.
