### ISSUE TITLE
Handle dynamic project metadata

### ISSUE THREAD

**Issue by nbraud** [duckinator/bork#339]
`bork build` fails if `pyproject.toml` doesn't contain `project.name`.

While [PEP 621] guarantees that `name` is (statically) defined *if the `project` table exists,* it also specifies
> The lack of a [project] table implicitly means the build back-end will dynamically provide all fields.

In that case, `bork` should call `{build-backend}.prepare_metadata_for_build_wheel`
and extract the metadata from the `.dist-info` directory that was populated.

[PEP 621]: https://peps.python.org/pep-0621/#specification

**Comment by duckinator** [comment]
Oh, this means we can probably remove all remaining traces of setup.cfg, nice!

**Comment by duckinator** [comment]
As @AstraLuma mentions in #349:

> bork zipapps require that a project table appears in pyproject.toml. Poetry-based projects use tool.poetry instead.

So an example project using Poetry would provide a good testcase for this functionality.

**Comment by duckinator** [comment]
#352 appears to be a manifestation of this.
