### ISSUE TITLE
project table required

### ISSUE THREAD

**Issue by AstraLuma** [duckinator/bork#349]
bork zipapps require that a `project` table appears in `pyproject.toml`. Poetry-based projects use `tool.poetry` instead.

**Comment by duckinator** [comment]
https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata

> The lack of a [project] table implicitly means the [build backend](https://packaging.python.org/en/latest/glossary/#term-Build-Backend) will dynamically provide all keys.

It sounds like this is a subset of #339. I'm leaving this open because it's a concrete, distinct example that would be useful to add tests for.

**Comment by duckinator** [comment]
Okay, it helps if I _read_ #339 in its entirety, maybe. This is a duplicate of that, but with a few more details. I'm going to add some info to #339 then close this issue.

**Comment by duckinator** [comment]
Closing as a duplicate of #339.
