### ISSUE TITLE
bork run could color stderr

### ISSUE THREAD

**Issue by nbraud** [duckinator/bork#52]
When running interactively, it's hard to distinguish the output on `bork run` on `stdout` and `stderr`.
Do you think it would be a good idea to automatically colorise `stderr` (say, in red?) while still letting commands override it (i.e. if a command sets a color, it should be honored).

Looks like there are libraries that produce cross-platform terminal color (like `colorama`), but I can't find anything that provides a colored, `stderr`-like object. Though perhaps what I'm looking for is actually a logging lib...

**Comment by duckinator** [comment]
I'm okay with this, but unsure of how to approach it.

**Comment by duckinator** [comment]
This was closed a while ago by #56.
