### ISSUE TITLE
Improve how bork.builder.zipapp() gets version information

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#61]
At the moment, `bork.builder.zipapp()` assumes `bork.builder.dist()` is called first _exclusively_ because it uses the generated sdist file to determine the version number.

We should, uh, probably not do that, because it's incredibly silly.

Related: https://github.com/duckinator/bork/pull/59

**Comment by astronouth7303** [comment]
I've looked into that for GoBuild.it. If you assume setuptools, there's some commands to produce the metadata directories (`dist_info` and `egg_info`). If you're assuming PEP517, there aren't universal ways to get the metadata about a project--you have to build a distribution first.

Like, the way I plan to architect pipelines is to build the sdist and linux+amd64 bdist first and then examine those to determine if GB.i should run additional builds.

**Comment by duckinator** [comment]
Looked into this a bit more and, yeah, seems there's no way to get the info without building a distribution first. I think the best that can be done is improving this glob: https://github.com/duckinator/bork/blob/master/bork/builder.py#L29

**Comment by duckinator** [comment]
At this point I've forgotten what the better glob would be. Should uh, probably figure that out at some point lmao

**Comment by duckinator** [comment]
Since we actively use the bdist during zipapp creation now (https://github.com/duckinator/bork/pull/202), this function was changed to use the bdist. So it feels less silly for it to require `bork.builder.dist()` to be called first.
