### ISSUE TITLE
Allow specifying which console_script entrypoint to use

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#9]
Allow the ability to specify the name of a `console_script` entrypoint, and using the definition of that.

This avoids duplicating it, which means you won't have to worry about keeping the two in sync.

**Comment by nbraud** [comment]
@duckinator I'm confused, what is the issue talking about?

**Comment by duckinator** [comment]
Given the move to pyproject.toml, this isn't relevant any more. And, realistically, it was a pretty minor problem to start with.

But basically, with the old setup.cfg setup, you'd have

```
console_scripts =
    bork = bork.cli:main
```

in one spot, and then `zipapp_main = "bork.cli:main"` in a different spot.

But, like I said, not relevant since we're moving to pyproject.toml. I'm gonna go ahead and close this.
