### ISSUE TITLE
Feature Request: Container

### ISSUE THREAD

**Issue by astronouth7303** [duckinator/bork#90]
I just did the thing where I have a multi-stage Dockerfile, and one of the stages is "run `bork build` on my project.

Any chance of a bork container?

**Comment by astronouth7303** [comment]
For the record, my solution for this is https://github.com/xonsh/container

**Comment by duckinator** [comment]
I'm hoping to have bork be distributable via zipapp, eventually, which would make a 'bork container' be just like this (completely untested):

```
FROM python:3.8-slim

ADD https://github.com/duckinator/bork/releases/download/latest/bork.pyz /

RUN /bork.pyz
```

**Comment by duckinator** [comment]
This should work, actually:

```
FROM python:3.8-slim

RUN pip3 install bork

ENTRYPOINT /usr/local/bin/bork
```

... not sure why I was over-complicating it before lol

**Comment by astronouth7303** [comment]
I would use `CMD` instead of `ENTRYPOINT`? entrypoint is gonna wreck havoc with CI.

**Comment by duckinator** [comment]
discovery: my general approach to this so far is... Not Great™... because it both runs before the release is done and expects the release to have already finished.

So basically after each version bump I have to go back and re-run the build once the release is done lmao

**Comment by duckinator** [comment]
The container should be automagically built when a new tag is pushed, if the corresponding PyPI release already exists.

The required workflow for everything to work properly is to merge a PR bumping the version number, then (from a local clone of Bork):

```
$ git checkout master
$ git pull
$ git tag v$(cut -d '"' -f 2 < bork/__init__.py)
$ bork run test && bork clean && bork build && bork release
$ # wait for `pip3 search bork` to find the correct version
$ git push --tags # causes Cirrus CI to build+push the Docker container
$ xdg-open "https://github.com/duckinator/bork/releases/new?tag=v$(cut -d '"' -f 2 < bork/__init__.py)" # Open page to create new GitHub Release
```

**Comment by duckinator** [comment]
I believe I've simplified the process a bit more. The `xdg-open` command will open a URL in the default web browser which creates a new tag + release in one go. This, again, assumes there's been a version bump merged already.

```
$ git checkout master && git pull
$ bork clean && bork build && bork run test && bork release
$ # wait for `pip3 search bork` to find the correct version
$ xdg-open "https://github.com/duckinator/bork/releases/new?revision=$(git rev-parse --short HEAD)&tag=v$(cut -d '"' -f 2 < bork/__init__.py)"
```

**Comment by duckinator** [comment]
@astronouth7303 could you poke at `duckinator/bork:v4.0.2` when you have some time and lmk if it does what you need? The `latest` tag is outdated right now, but the next release includes #161 which should fix that moving forward.

**Comment by astronouth7303** [comment]
Can it get `git`? Kinda needed for `setuptools-scm` and conceptually similar stuff

**Comment by duckinator** [comment]
@astronouth7303 next bork release should have a Docker image with both correct `latest` tag and `git`.

**Comment by duckinator** [comment]
Releasing v5.0.0 today, and it's worked for multiple beta releases, so I'm considering this resolved. :+1:
